infrastructure: ^3
shared_dirs:
  mysite:
    testfolder: {}
apache:
  prefork:
    startservers: "4"
    minspareservers: "3"
    maxspareservers: "7"
    maxclients: "35"
    serverlimit: "35"
    maxrequestsperchild: "20000"
crons:
  mytask:
    time: "0 20 * * *"
    command: "echo \"test cron run 123\" | logger -t SilverStripe_cron"
http_settings:
  max_upload_size: "128"
  timezone: "Pacific/Auckland"
php_settings:
  version: 7.1
  cli:
    memory_limit: "2048M"
